CC=m68k-amigaos-gcc
STRIP=m68k-amigaos-strip
RM=rm -f

CFLAGS=-I. -Isrc -Iinclude -O2 -Wall -Wno-pointer-sign -Wno-incompatible-pointer-types -Werror -mcpu=68000
ifeq ($(DEBUG), 1)
CFLAGS+=-DDEBUG
endif
LDFLAGS=-noixemul -mcpu=68000
LIBS=-lamiga
ifeq ($(ENABLE_MUI), 1)
LIBS+=-lmui
endif

ifeq ($(ENABLE_MUI), 1)
TARGET=Executer_mui
else
TARGET=Executer
endif

include common.mk
